scene.setBackgroundColor(8)
let spacePlane = sprites.create(img`
    ........................................
    ........................................
    ........................................
    ....................ffff................
    ..................ffddddff..............
    .................fddddd11df.............
    .................fdddddd11df............
    ...........ffff.fdddddddd1df............
    .........ffddddffddddddddddf............
    ........fddddd11dfdddddddddf............
    ........fdddddd11fdddddddddf............
    .......fdddddddd1dfdddddddf.............
    .......fddddddddddfddddddf2f............
    .......fddddddddddfdddddff22f.f.........
    .......fddddddddddfdddfff5f22fdf........
    .......fddddddddddffff55f5f22fdf........
    ........fddddddffff5555f5ffffff.........
    .......f2ffffff5555555f5f5f.............
    ......f22f5555555555555555f.............
    ...ff.f22f55ff5555555555ff..............
    ...fdff2ff5f555555f55fff................
    ...fddff.f55f55555fffddf................
    ....ff...f55555ffffdddf.................
    .........f55fffddf1fdf..................
    ..........ff..fdff11f...................
    ...............f1f1f....................
    ..............f9f9f.....................
    .............f99f99f....................
    ............f99f.f99f...................
    .............ff...fff...................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
`, SpriteKind.Player)
info.setLife(3)
spacePlane.setStayInScreen(true)
controller.moveSprite(spacePlane, 200, 200)
controller.A.onEvent(ControllerButtonEvent.Pressed, function on_a_pressed() {
    let missile = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . .
            . . . . . . . f f f f f f . . .
            . . . . . . f f 5 5 5 f f . . .
            . . . . . f 5 5 5 1 5 5 f . . .
            . . . . f 5 5 5 5 5 5 5 f . . .
            . . . f 5 5 5 5 5 5 5 5 f . . .
            . . . . f f 5 5 5 5 5 5 f . . .
            . . . . . f f 5 5 5 5 5 f . . .
            . . . . . . f 5 5 5 5 5 f . . .
            . . . . . . . f f f f f . . . .
            . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . .
        `, spacePlane, 200, 0)
})
game.onUpdateInterval(500, function on_update() {
    let bogy = sprites.create(assets.image`hand`, SpriteKind.Enemy)
    bogy.setVelocity(-100, randint(-30, 30))
    bogy.y = randint(0, scene.screenHeight())
    bogy.left = scene.screenWidth()
    bogy.setFlag(SpriteFlag.AutoDestroy, true)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function on_hit(sprite: Sprite, othersprite: Sprite) {
    othersprite.destroy(effects.fire, 100)
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function on_crash(sprite: Sprite, othersprite: Sprite) {
    othersprite.destroy()
    info.changeLifeBy(-1)
})
